sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
  # minimum supported version
  - "1.45.0"
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add rustfmt

script:
  - cargo build
  - cargo build --examples
  - cargo test
  - cargo fmt -- --check
  - python3 scripts/test.py --debug --verbose
